CREATE TEMPORARY TABLESPACE TS_CINEMA
----TEMPFILE 'D:\Tablespaces\TS_KKVTEMP_LAB3.dbf'
----SIZE 5M
----AUTOEXTEND ON NEXT 3M
----MAXSIZE 30M
----EXTENT MANAGEMENT LOCAL;

CREATE ROLE c##RL_KKVPDB;
GRANT CREATE SESSION, CREATE ANY TABLE, DROP ANY TABLE,
CREATE ANY VIEW, DROP ANY VIEW, CREATE ANY PROCEDURE, DROP ANY PROCEDURE 
TO c##RL_KKVPDB;

CREATE ROLE c##RL_KKVPDB;
GRANT CREATE SESSION, CREATE ANY TABLE, DROP ANY TABLE,
CREATE ANY VIEW, DROP ANY VIEW, CREATE ANY PROCEDURE, DROP ANY PROCEDURE 
TO c##RL_KKVPDB;

CREATE ROLE c##RL_KKVPDB;
GRANT CREATE SESSION, CREATE ANY TABLE, DROP ANY TABLE,
CREATE ANY VIEW, DROP ANY VIEW, CREATE ANY PROCEDURE, DROP ANY PROCEDURE 
TO c##RL_KKVPDB;

CREATE PROFILE c##PF_KKVPDB LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30


CREATE USER c##U1_KKV_PDB IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_KKV_LAB3 QUOTA UNLIMITED ON TS_KKV_LAB3
TEMPORARY TABLESPACE TS_KKVTEMP_LAB3
PROFILE c##PF_KKVPDB
ACCOUNT UNLOCK
GRANT c##RL_KKVPDB TO c##U1_KKV_PDB;
